apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # "root"
  MYSQL_ROOT_PASSWORD: cm9vdA==
  # "testdb"
  MYSQL_DATABASE: dGVzdGRi
  # "user"
  MYSQL_USER: dXNlcg==
  # "password"
  MYSQL_PASSWORD: cGFzc3dvcmQ=
